FROM jboss/keycloak:11.0.2

ADD cli/TCPPING.cli /opt/jboss/tools/cli/jgroups/discovery/

ADD cli/JDBC_PING_MYSQL.cli /opt/jboss/tools/cli/jgroups/discovery/
ADD cli/JDBC_PING_MARIADB.cli /opt/jboss/tools/cli/jgroups/discovery/
ADD cli/JDBC_PING_POSTGRES.cli /opt/jboss/tools/cli/jgroups/discovery/